Pinterest/models.py
from Pinterest import db,login_manager, app
from sqlalchemy.sql import func
from flask_login import UserMixin



@login_manager.user_loader
def load_usuario(id_usuario):
    return User.query.get(int(id_usuario))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    imgs = db.relationship('Img', backref='user', passive_deletes=True, lazy=True)
    


class Img(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    image = db.Column(db.String(150), default="default.png")
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    id_user = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"), nullable=False)

with app.app_context():
    db.create_all()

Pinterest/forms.py
from flask_wtf import FlaskForm
from flask import flash
from wtforms import StringField,SubmitField,PasswordField,FileField
from wtforms.validators import DataRequired, Email, EqualTo, Length, ValidationError
from .models import User

class FormLogin(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    button = SubmitField('Login')


class FormSign(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), Length(8, 20)])
    confirm_password = PasswordField('Confirm_password', validators=[DataRequired(), EqualTo('password')])
    button = SubmitField('Sign up')

    def validate_email(self,email):
        user =  User.query.filter_by(email=email).first()
        if user:
            return ValidationError(flash('Email já cadastrado'))

class FormImg(FlaskForm):
    img = FileField("Foto", validators=[DataRequired()])
    button = SubmitField("Enviar")

Pinterest/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
from dotenv import load_dotenv
from flask_login import LoginManager
from flask_bcrypt import Bcrypt


load_dotenv()

DB_NAME = os.environ.get('DB_NAME') 


app =  Flask(__name__)
app.config['SECRET_KEY'] = "pinterest"

bcrypt = Bcrypt(app)

login_manager = LoginManager(app)
login_manager.login_view = "homepage"

db = SQLAlchemy()


app.config['SQLALCHEMY_DATABASE_URI'] = f"mysql+pymysql://root:root@localhost/{DB_NAME}"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config["UPLOAD_FOLDER"] = "static/fotos_posts"

db.init_app(app)


from .views import views
app.register_blueprint(views, url_prefix="/")

Pinterest/views.py
from flask import Flask,render_template,url_for, Blueprint,redirect,flash
from flask_login import login_required, login_user, logout_user, current_user
from Pinterest import bcrypt, db,app
from Pinterest.forms import  FormLogin,FormSign,FormImg
from Pinterest.models import  User, Img
from werkzeug.utils import secure_filename
import os

views = Blueprint("views", __name__)

@views.route("/", methods=['GET', 'POST'])
@views.route("/homepage", methods=['GET', 'POST'])
def homepage():
    """
    Displays the homepage and allows the user to log in.
    """
    form_login = FormLogin()
    if form_login.validate_on_submit():
        db_user = User.query.filter_by(email=form_login.email.data).first()
        if db_user and bcrypt.check_password_hash(db_user.password, form_login.password.data):
            login_user(db_user, remember=True)
            return redirect(url_for('views.perfil', user_id=db_user.id))
        else:
            flash('No user with this email')
            return redirect(url_for('views.creat_account'))

    return render_template('homepage.html', form=form_login)

@views.route("/creat_account", methods=['GET', 'POST'])
def creat_account():
    """
    Displays the signup form and creates a new user when the form is submitted.
    """
    form_sign = FormSign()
    if form_sign.validate_on_submit():
        try:
            hashed_password  = bcrypt.generate_password_hash(form_sign.password.data).decode('utf-8')
            user = User(email=form_sign.email.data, username=form_sign.username.data, password=hashed_password )
            db.session.add(user)
            db.session.commit()
            login_user(user, remember=True)
            flash('Account created successfully!', 'success')
            return redirect(url_for('views.perfil', user_id=user.id))
        except:
            db.session.rollback()
            flash('Error creating account. Please try again later.')
            return redirect(url_for('views.homepage'))
    return render_template('creat_account.html', form=form_sign)

@views.route("/logout", methods=['GET', 'POST'])
@login_required
def logout():
    """
    Logs out the user and redirects to the homepage.
    """
    logout_user()
    return redirect(url_for('views.homepage'))

@views.route("/perfil/<int:user_id>", methods=['GET', 'POST'])
def perfil(user_id):
    if user_id == current_user.id:
        # User looking at own profile
        form_img = FormImg()
        if form_img.validate_on_submit():
            try:
                file = form_img.img.data
                secure_name = secure_filename(file.filename)
                path = os.path.join(os.path.abspath(os.path.dirname(__file__)), app.config["UPLOAD_FOLDER"], secure_name)
                file.save(path)
                img = Img(image=secure_name, id_user=current_user.id)
                db.session.add(img)
                db.session.commit()
                flash('Image uploaded successfully!', 'success')
            except Exception as e:
                flash(f'Error uploading image: {str(e)}', 'danger')
        return render_template('perfil.html', user=current_user, form=form_img)
    else:
        user = User.query.get(user_id)
        return render_template('perfil.html', user=user)

@views.route("/feed", methods=['GET', 'POST'])
@login_required
def feed():
    """
    Displays the all images in a  feed for the logged-in user.
    """
    imgs =  Img.query.order_by(Img.date_created).all()
    return render_template('feed.html', fotos=imgs)

Pinterest/templates/creat_account.html
{% extends "homepage.html" %}

{% block titulo %}
FakePinterest - Criar Conta
{% endblock %}

 {% block formulario %}

        <form method="POST" class="popup">
            {{ form.csrf_token }}
          <svg
            height="40"
            viewBox="-3 -3 82 82"
            width="40"
            style="display: block"
          >
            <title>Pinterest logo</title>
            <circle cx="38" cy="38" fill="white" r="40"></circle>
            <path
              d="M27.5 71c3.3 1 6.7 1.6 10.3 1.6C57 72.6 72.6 57 72.6 37.8 72.6 18.6 57 3 37.8 3 18.6 3 3 18.6 3 37.8c0 14.8 9.3 27.5 22.4 32.5-.3-2.7-.6-7.2 0-10.3l4-17.2s-1-2-1-5.2c0-4.8 3-8.4 6.4-8.4 3 0 4.4 2.2 4.4 5 0 3-2 7.3-3 11.4C35.6 49 38 52 41.5 52c6.2 0 11-6.6 11-16 0-8.3-6-14-14.6-14-9.8 0-15.6 7.3-15.6 15 0 3 1 6 2.6 8 .3.2.3.5.2 1l-1 3.8c0 .6-.4.8-1 .4-4.4-2-7-8.3-7-13.4 0-11 7.8-21 22.8-21 12 0 21.3 8.6 21.3 20 0 12-7.4 21.6-18 21.6-3.4 0-6.7-1.8-7.8-4L32 61.7c-.8 3-3 7-4.5 9.4z"
              fill="#e60023"
              fill-rule="evenodd"
            ></path>
          </svg>

          <h2>Bem-vindo(a) ao FakePinterest</h2>

          <div class="div-input">
              {{ form.email.label(class="label") }}
                {{ form.email(class="input") }}
          </div>

            <div class="div-input">
              {{ form.username.label(class="label") }}
                {{ form.username(class="input") }}
          </div>

          <div class="div-input">
            {{ form.password.label(class="label") }}
            {{ form.password(class="input") }}
          </div>

          <div class="div-input">
            {{ form.confirm_password.label(class="label") }}
            {{ form.confirm_password(class="input") }}
          </div>


          <div class="div-botao">
              {{ form.button(class="botao-login") }}
            <a href="{{ url_for('views.homepage') }}" class="link-criarconta">Já tem uma conta? Faça Login</a>
          </div>

        </form>
          {% endblock %}

Pinterest/templates/feed.html
{% extends "homepage.html" %}


{% block body %}
{% include "navbar.html" %}

  <body>
    <div class="container">


      <div class="conteudo">
          {% for foto in fotos %}
            <a href="{{ url_for('views.perfil', user_id=foto.id_user) }}" class="bloco-imagem">
              <img src="{{ url_for('static', filename='fotos_posts/{}'.format(foto.image)) }}" />
            </a>
          {% endfor %}
      </div>
    </div>
  </body>

{% endblock %}

Pinterest/templates/homepage.html
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>{% block titulo %}
        FakePinterest
        {% endblock %}</title>
  </head>

{% block body %}
  <body class="overflow-hidden">
    <div class="container">
      <header>
        <nav>
          <div class="logo-pinterest">
            <svg
              height="40"
              viewBox="-3 -3 82 82"
              width="40"
              style="display: block"
            >
              <title>FakePinterest logo</title>
              <circle cx="38" cy="38" fill="white" r="40"></circle>
              <path
                d="M27.5 71c3.3 1 6.7 1.6 10.3 1.6C57 72.6 72.6 57 72.6 37.8 72.6 18.6 57 3 37.8 3 18.6 3 3 18.6 3 37.8c0 14.8 9.3 27.5 22.4 32.5-.3-2.7-.6-7.2 0-10.3l4-17.2s-1-2-1-5.2c0-4.8 3-8.4 6.4-8.4 3 0 4.4 2.2 4.4 5 0 3-2 7.3-3 11.4C35.6 49 38 52 41.5 52c6.2 0 11-6.6 11-16 0-8.3-6-14-14.6-14-9.8 0-15.6 7.3-15.6 15 0 3 1 6 2.6 8 .3.2.3.5.2 1l-1 3.8c0 .6-.4.8-1 .4-4.4-2-7-8.3-7-13.4 0-11 7.8-21 22.8-21 12 0 21.3 8.6 21.3 20 0 12-7.4 21.6-18 21.6-3.4 0-6.7-1.8-7.8-4L32 61.7c-.8 3-3 7-4.5 9.4z"
                fill="#e60023"
                fill-rule="evenodd"
              ></path>
            </svg>
            <h1>FakePinterest</h1>
          </div>

          <div class="restante-nav">
            <a href="" class="link-nav">About</a>
            <a href="" class="link-nav">Business</a>
            <a href="" class="link-nav">Blog</a>
          </div>
        </nav>
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %} {% for category, message in messages %} {% if category ==
          'error' %}
          <div class="alert alert-danger alter-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </div>
          {% else %}
          <div class="alert alert-success alter-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          </div>
          {% endif %} {% endfor %} {% endif %} {% endwith %}
      </header>

      <img src="{{ url_for('static', filename='fotos_site/fundo-login.png') }}" class="bg-imagem-pinterest" />

      <div class="container-popup">

          {% block formulario %}

        <form method="POST" class="popup">
            {{ form.csrf_token }}
          <svg
            height="40"
            viewBox="-3 -3 82 82"
            width="40"
            style="display: block"
          >
            <title>Pinterest logo</title>
            <circle cx="38" cy="38" fill="white" r="40"></circle>
            <path
              d="M27.5 71c3.3 1 6.7 1.6 10.3 1.6C57 72.6 72.6 57 72.6 37.8 72.6 18.6 57 3 37.8 3 18.6 3 3 18.6 3 37.8c0 14.8 9.3 27.5 22.4 32.5-.3-2.7-.6-7.2 0-10.3l4-17.2s-1-2-1-5.2c0-4.8 3-8.4 6.4-8.4 3 0 4.4 2.2 4.4 5 0 3-2 7.3-3 11.4C35.6 49 38 52 41.5 52c6.2 0 11-6.6 11-16 0-8.3-6-14-14.6-14-9.8 0-15.6 7.3-15.6 15 0 3 1 6 2.6 8 .3.2.3.5.2 1l-1 3.8c0 .6-.4.8-1 .4-4.4-2-7-8.3-7-13.4 0-11 7.8-21 22.8-21 12 0 21.3 8.6 21.3 20 0 12-7.4 21.6-18 21.6-3.4 0-6.7-1.8-7.8-4L32 61.7c-.8 3-3 7-4.5 9.4z"
              fill="#e60023"
              fill-rule="evenodd"
            ></path>
          </svg>

          <h2>Bem-vindo(a) ao FakePinterest</h2>

          <div class="div-input">
              {{ form.email.label(class="label") }}
                {{ form.email(class="input") }}
          </div>

          <div class="div-input">
            {{ form.password.label(class="label") }}
            {{ form.password(class="input") }}
          </div>

          <div class="div-botao">
              {{ form.button(class="botao-login") }}
            <a href="{{ url_for('views.creat_account') }}" class="link-criarconta">Não tem uma conta? Crie aqui</a>
          </div>

        </form>
          {% endblock %}

      </div>
    </div>
  </body>
{% endblock %}
</html>

Pinterest/templates/navbar.html
<header>
        <nav>
          <a href="{{ url_for('views.feed') }}" class="logo-pinterest" style="text-decoration: none;">
            <svg
              height="40"
              viewBox="-3 -3 82 82"
              width="40"
              style="display: block"
            >
              <title>FakePinterest logo</title>
              <circle cx="38" cy="38" fill="white" r="40"></circle>
              <path
                d="M27.5 71c3.3 1 6.7 1.6 10.3 1.6C57 72.6 72.6 57 72.6 37.8 72.6 18.6 57 3 37.8 3 18.6 3 3 18.6 3 37.8c0 14.8 9.3 27.5 22.4 32.5-.3-2.7-.6-7.2 0-10.3l4-17.2s-1-2-1-5.2c0-4.8 3-8.4 6.4-8.4 3 0 4.4 2.2 4.4 5 0 3-2 7.3-3 11.4C35.6 49 38 52 41.5 52c6.2 0 11-6.6 11-16 0-8.3-6-14-14.6-14-9.8 0-15.6 7.3-15.6 15 0 3 1 6 2.6 8 .3.2.3.5.2 1l-1 3.8c0 .6-.4.8-1 .4-4.4-2-7-8.3-7-13.4 0-11 7.8-21 22.8-21 12 0 21.3 8.6 21.3 20 0 12-7.4 21.6-18 21.6-3.4 0-6.7-1.8-7.8-4L32 61.7c-.8 3-3 7-4.5 9.4z"
                fill="#e60023"
                fill-rule="evenodd"
              ></path>
            </svg>
            <h1>FakePinterest</h1>
          </a>

          <div class="restante-nav">
            <p class="botao-perfil"><a href="{{ url_for('views.perfil', user_id=current_user.id) }}" class="link-nav">Perfil</a></p>
            <a href="{{ url_for('views.logout') }}" class="link-nav">Sair</a>
          </div>
        </nav>
      </header>

Pinterest/templates/perfil.html
{% extends "homepage.html" %}

{% block titulo %}
Perfil - {{ user.username }}
{% endblock %}

{% block body %}
<body>
{% include "navbar.html" %}
<div class="container">

{% if form %}


      <form class="bloco-add-img" method="POST" enctype="multipart/form-data">
          {{ form.csrf_token }}
        <h2>{{ user.username }} - Enviar foto</h2>

        <div class="bloco-arquivo">
            <label for="foto" class="botao-arquivo">
              Escolher arquivo
                {{ form.img(class="input-arquivo", id="foto") }}
            </label>
            <span id="imagem-arquivo" class=""></span>
          </div>

          {{ form.button(class="botao-login") }}
        </form>

{% else %}
<div class="bloco-add-img">
    <h2>{{ user.username }} - Ver Perfil</h2>
</div>
{% endif %}



<div class="conteudo">
{% for foto in user.imgs %}
    <div class="bloco-imagem">
      <img src="{{ url_for('static', filename='fotos_posts/{}'.format(foto.image)) }}" />
    </div>
{% endfor %}
    </div>

</div>

  <script>
      let input = document.getElementById("foto");
      let imagemArquivo = document.getElementById("imagem-arquivo");

      input.addEventListener("change", () => {
        let inputImagem = document.querySelector("input[type=file]").files[0];

        imagemArquivo.classList.add("visivel");
        imagemArquivo.innerText = inputImagem.name;
      });
    </script>
</body>
{% endblock %}